import {writeFile} from 'node:fs/promises';
import {parseGameval} from '../src/core/gameval.mjs';

const get=async url=>{
  const response=await fetch(url,{signal:AbortSignal.timeout(30000)});
  if(!response.ok)throw new Error(`RuneLite returned ${response.status}: ${url}`);
  return response;
};
const revision=process.argv[2]??(await (await get('https://api.github.com/repos/runelite/runelite/commits/master')).json()).sha;
if(!/^[a-f0-9]{40}$/.test(revision))throw new Error('Provide a full RuneLite commit SHA.');
const path='runelite-api/src/main/java/net/runelite/api/gameval';
const files=['ObjectID','ObjectID1','NpcID'];
const sources=await Promise.all(files.map(async file=>(await get(`https://raw.githubusercontent.com/runelite/runelite/${revision}/${path}/${file}.java`)).text()));
if(!/public final class ObjectID extends ObjectID1\b/.test(sources[0]))throw new Error('Review the changed ObjectID class hierarchy before refreshing.');
const names={GAME_OBJECT:[],NPC:[]};
for(let i=0;i<files.length;i++)for(const entry of parseGameval(sources[i],files[i],revision))names[entry.objectType][Number(entry.id)]??=entry.name;
// Dense ID tables avoid tens of thousands of object-property declarations in the browser bundle.
const output=`// Generated by scripts/refresh-gameval.mjs. Do not edit by hand.\n// RuneLite gameval sources: https://github.com/runelite/runelite/tree/${revision}/${path}\nexport const GAMEVAL_REVISION=${JSON.stringify(revision)};\nexport const OBJECT_NAMES=${JSON.stringify(names.GAME_OBJECT.join('|'))}.split('|');\nexport const NPC_NAMES=${JSON.stringify(names.NPC.join('|'))}.split('|');\n`;
await writeFile(new URL('../src/core/gameval-ids.mjs',import.meta.url),output);
console.log(`Pinned ${names.GAME_OBJECT.filter(Boolean).length} object and ${names.NPC.filter(Boolean).length} NPC constants at ${revision}.`);
