import { useLayoutEffect, useState } from 'react';
import EncounterMaps from './EncounterMaps';
import EntranceEditor from './Entrance';
import { CoveragePanel, SourcesPanel } from './Inspector';
import { Icon } from './Icons';
import BossPortrait, { BossImageSource } from './BossPortrait';
import { exportProblem } from './core/authoring.mjs';
import { overlapWarnings } from './core/proposal.mjs';
import type { Boss, Draft, Snapshot } from './types';

export type AuthoringStep = 'coverage' | 'entrance' | 'review';
type Props = {
  boss: Boss; draft: Draft; snapshot: Snapshot; saved: boolean; busy: string;
  step: AuthoringStep; setStep: (step: AuthoringStep) => void;
  update: (change: Partial<Draft>) => void; onLoad: () => void; onError: (message: string) => void;
  onBack: () => void; onDiscard: () => void; onUndo: () => void; onRedo: () => void;
  canUndo: boolean; canRedo: boolean; preview: string;
  onExport: (kind: string, ids: string[]) => void; onSelect: (boss: Boss) => void; bosses: Boss[];
};

export default function Authoring(p: Props) {
  const { boss, draft, step, setStep } = p;
  useLayoutEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }); }, [step]);
  const [showSources, setShowSources] = useState(false);
  const preservedEntrance = boss.optionalArgs.some(a => a.includes('RegionEntrance('));
  const readOnly = (!!boss.raw && boss.regionType !== 'BOSSES') || (!boss.raw && !!boss.supportedBy?.length);
  const issue = exportProblem(p.snapshot, [draft]);
  const warnings = overlapWarnings([draft], p.snapshot.entries);
  const steps: { id: AuthoringStep; label: string; description: string; done: boolean }[] = [
    { id: 'coverage', label: 'Arena coverage', description: 'Where the fight happens', done: draft.regions.length > 0 && !!draft.deathType },
    { id: 'entrance', label: 'Entrance', description: 'Optional object detection', done: !!draft.entrance?.ids.length || preservedEntrance },
    { id: 'review', label: 'Review & export', description: 'Check and share your work', done: !issue },
  ];
  return <section className="authoring" aria-label="Encounter authoring">
    <div className="authoring-header"><div><button className="back-discovery" onClick={p.onBack}>← Encounter library</button><div className="authoring-title"><BossPortrait boss={boss} compact/><h1>{draft.name}</h1><span className={`save-state ${p.saved ? 'is-saved' : ''}`}><Icon name={p.saved ? 'check' : 'file'} size={14}/>{p.saved ? 'Draft saved in this browser' : 'No changes yet'}</span></div></div><div className="authoring-utilities"><button disabled={!p.canUndo} onClick={p.onUndo} aria-label="Undo edit">↶ Undo</button><button disabled={!p.canRedo} onClick={p.onRedo} aria-label="Redo edit">↷ Redo</button><button aria-pressed={showSources} onClick={() => setShowSources(v => !v)}><Icon name="book" size={16}/> Sources <span className="count">{boss.maps.length}</span></button></div></div>
    <nav className="authoring-steps" aria-label="Authoring steps">{steps.map((s, i) => <button key={s.id} aria-current={step === s.id ? 'step' : undefined} className={`${step === s.id ? 'current' : ''} ${s.done ? 'configured' : ''}`} onClick={() => setStep(s.id)}><span className="step-number">{s.done ? <Icon name="check" size={15}/> : i + 1}</span><span><strong>{s.label}</strong><small>{s.description}</small></span>{i < 2 && <Icon name="arrow" size={16}/>}</button>)}</nav>
    {readOnly && <div className="authoring-readonly"><Icon name="shield"/><div><strong>{boss.supportedBy?.length ? 'This encounter uses shared coverage.' : 'This entry is read-only in the boss editor.'}</strong><p>{boss.supportedBy?.length ? 'Edit the existing shared entry to update its coverage.' : 'This entry belongs to another plugin category.'}</p>{boss.supportedBy?.map(s => { const target = p.bosses.find(b => b.id === s.id); return target && <button key={s.id} onClick={() => p.onSelect(target)}>Edit {s.name} <Icon name="arrow" size={14}/></button>; })}</div></div>}
    {showSources && <section className="authoring-sources"><div className="source-drawer-heading"><strong>Location evidence</strong><button onClick={() => setShowSources(false)} aria-label="Close sources"><Icon name="close" size={16}/></button></div><BossImageSource title={boss.wikiTitle}/><SourcesPanel boss={boss}/></section>}
    {step !== 'review' ? <div className={`authoring-body ${step === 'entrance' ? 'entrance-step' : ''}`}>
      <div className="authoring-map"><div className="work-heading"><div><h2>{step === 'coverage' ? 'Select the fight area' : 'Locate the entrance'}</h2><p>{step === 'coverage' ? 'Click regions to include them. Click again to remove them.' : 'Choose the entrance region, then pick a nearby object.'}</p></div><button disabled={!!p.busy} onClick={p.onLoad}><Icon name="sync" size={14}/>{p.busy ? 'Loading…' : boss.maps.length ? 'Refresh locations' : 'Load locations'}</button></div><EncounterMaps key={boss.id} boss={boss} draft={draft} update={p.update} onError={p.onError} onLoad={p.onLoad} focus={step === 'coverage' ? 'arena' : 'entrance'} loading={!!p.busy}/><div className="map-help"><Icon name="map" size={16}/><span>Pan to explore · Select a region or use coordinates · Check source locations in game</span></div></div>
      <aside className="authoring-inspector"><fieldset disabled={readOnly} className="authoring-fields">{step === 'coverage' ? <CoveragePanel key={boss.id} draft={draft} update={p.update} deaths={[...new Set(p.snapshot.entries.map(b => b.deathType))]} preview={p.preview} canDiscard={p.saved} onDiscard={p.onDiscard} guided/> : <EntranceEditor key={boss.id} boss={boss} draft={draft} update={p.update} onError={p.onError} guided/>}</fieldset></aside>
    </div> : <div className="review-workspace"><div className="review-content"><div className="work-heading"><div><h2>Check your encounter</h2><p>Review the final settings before creating a contribution.</p></div><span className={`review-readiness ${issue ? 'pending' : 'ready'}`}><Icon name={issue ? 'file' : 'check'} size={15}/>{issue ? 'Review needed' : 'Ready to export'}</span></div>
      <section className="review-summary-card"><div><Icon name="map"/><h3>Arena coverage</h3><button onClick={() => setStep('coverage')}>Edit coverage</button></div><dl><dt>Regions</dt><dd>{draft.regions.join(', ') || 'None selected'}</dd><dt>Death behavior</dt><dd>{draft.deathType === 'UNSAFE' ? 'Unsafe death' : draft.deathType === 'UNSAFE_HCGIM' ? 'Unsafe for Hardcore Group Ironman' : draft.deathType || 'Not selected'}</dd><dt>Chunk restrictions</dt><dd>{draft.chunks?.length ? draft.chunks.join(', ') : 'Whole regions'}</dd></dl><label className={`review-check ${draft.reviewed ? 'complete' : ''}`}><input type="checkbox" checked={draft.reviewed} disabled={readOnly || !draft.regions.length || !draft.deathType} onChange={e => p.update({ reviewed: e.target.checked })}/><span>I verified the coverage and death behavior in game.<small>Wiki suggestions alone are not in-game verification.</small></span></label></section>
      <section className="review-summary-card"><div><Icon name="layers"/><h3>Entrance detection</h3><button onClick={() => setStep('entrance')}>Edit entrance</button></div>{draft.entrance ? <><dl><dt>Object / NPC IDs</dt><dd>{draft.entrance.ids.join(', ') || 'None selected'}</dd><dt>Interaction type</dt><dd>{draft.entrance.objectType.replaceAll('_', ' ').toLowerCase()}</dd><dt>Approach / plane</dt><dd>{draft.entrance.direction || 'Default'} / {draft.entrance.plane || 'Default'}</dd><dt>Chunk restrictions</dt><dd>{draft.entrance.chunks.join(', ') || 'None'}</dd></dl><label className={`review-check ${draft.entrance.reviewed ? 'complete' : ''}`}><input type="checkbox" checked={draft.entrance.reviewed} disabled={readOnly || !draft.entrance.ids.length} onChange={e => p.update({ entrance: { ...draft.entrance!, reviewed: e.target.checked } })}/><span>I verified the entrance IDs and variants in game.</span></label></> : <p>{preservedEntrance ? 'The existing plugin entrance is preserved.' : 'No entrance detection added. This contribution covers the arena only.'}</p>}</section>
      {warnings.map((w, i) => <p className="warning" key={i}>{w}</p>)}<details className="review-code"><summary>Compare generated code</summary>{boss.raw && <><h4>Current plugin entry</h4><pre>{boss.raw}</pre></>}<h4>Your draft</h4><pre>{p.preview}</pre></details>
    </div><aside className="export-card"><span className="eyebrow">SHARE YOUR CONTRIBUTION</span><h2>Export this encounter</h2><p>Export this encounter on its own. Other unfinished drafts won’t block you.</p>{issue && <div className="export-issue" role="status"><strong>Before you export</strong><p>{issue}</p></div>}<button className="primary" disabled={readOnly || !!issue || !p.saved} onClick={() => p.onExport('json', [draft.id])}><Icon name="file"/> Download proposal</button><button disabled={readOnly || !!issue || !p.saved} onClick={() => p.onExport('patch', [draft.id])}>Download patch</button><button disabled={readOnly || !!issue || !p.saved} onClick={() => p.onExport('copy', [draft.id])}>Copy proposal</button><p className="export-note">Nothing is submitted automatically. Send the proposal to a maintainer or use the plugin’s contribution workflow.</p><a href="https://github.com/Xylot/escape-crystal-notify/actions/workflows/content-proposal.yml" target="_blank" rel="noreferrer">Open maintainer workflow <Icon name="external" size={13}/></a></aside></div>}
    <footer className="authoring-footer"><div><span className="dot mint-dot"/><span>{p.saved ? 'Your changes are saved locally.' : 'Changes save automatically as you edit.'}</span></div><div>{step !== 'coverage' && <button onClick={() => setStep(step === 'review' ? 'entrance' : 'coverage')}>← Back</button>}{step === 'coverage' && <button onClick={() => setStep('review')}>Arena only · review</button>}{step === 'entrance' && <button onClick={() => { if(draft.entrance)p.update({entrance:undefined});setStep('review'); }}>{draft.entrance?'Remove entrance changes':preservedEntrance?'Keep existing entrance':'Skip entrance'}</button>}{step !== 'review' && <button className="primary" onClick={() => setStep(step === 'coverage' ? 'entrance' : 'review')}>{step === 'coverage' ? 'Continue to entrance' : 'Review encounter'} <Icon name="arrow" size={16}/></button>}{step === 'review' && <button onClick={p.onBack}>Back to library</button>}</div></footer>
  </section>;
}
