import {useState} from 'react';
import {parseIds} from './core/coordinates.mjs';
import ChunkEditor from './ChunkEditor';
import type {Boss,Draft} from './types';
export function CoveragePanel({draft,update,deaths,preview,onDiscard,canDiscard,guided=false}:{draft:Draft;update:(d:Partial<Draft>)=>void;deaths:string[];preview:string;onDiscard:()=>void;canDiscard:boolean;guided?:boolean}){
 const [manual,setManual]=useState(''),[error,setError]=useState('');
 return <div className="inspector-panel"><div className="inspector-heading"><h2>Coverage settings</h2><p>Regions and chunk restrictions for this encounter.</p></div><section className="inspector-card"><div className="inspector-card-title"><h3>Selected regions</h3><span>{draft.regions.length}</span></div><div className="region-chips">{draft.regions.map(id=><button key={id} onClick={()=>update({regions:draft.regions.filter(n=>n!==id)})} aria-label={`Remove region ${id}`}>{id} ×</button>)}{!draft.regions.length&&<p className="muted">Click an arena region to select it.</p>}</div><details className="inspector-disclosure" open={guided||undefined}><summary>Add region by ID</summary><form className="id-entry" onSubmit={e=>{e.preventDefault();try{update({regions:[...new Set([...draft.regions,...parseIds(manual)])].sort((a,b)=>a-b)});setManual('');setError('');}catch(e){setError((e as Error).message);}}}><input aria-label="Region IDs" placeholder="12682, 12938" value={manual} onChange={e=>setManual(e.target.value)}/><button>Add</button></form>{error&&<p role="alert" className="warning">{error}</p>}</details></section>
 {!guided&&<section className="inspector-card"><label className="field">Death classification<select value={draft.deathType} onChange={e=>update({deathType:e.target.value})}><option value="">Select behavior…</option>{deaths.map(t=><option key={t} value={t}>{t==='UNSAFE'?'Unsafe death':t==='UNSAFE_HCGIM'?'Unsafe for Hardcore Group Ironman':t==='SAFE'?'Safe death':t}</option>)}</select></label><p className="inspector-hint">Confirm instance coverage and escape-crystal behavior in game.</p></section>}
 <details className="inspector-disclosure"><summary>Advanced coverage</summary><label className="field">Display name<input value={draft.name} onChange={e=>update({name:e.target.value})}/></label><ChunkEditor draft={draft} update={update}/></details>{!guided&&<details className="inspector-disclosure"><summary>Generated Java</summary><pre>{preview}</pre></details>}<button className="discard-action" disabled={!canDiscard} onClick={onDiscard}>Discard this draft</button></div>;
}
export function SourcesPanel({boss}:{boss:Boss}){
 return <div className="inspector-panel"><div className="inspector-heading"><h2>Source evidence</h2><p>Check where each suggested location came from.</p></div>{!boss.maps.length&&<div className="inspector-card"><p>No location evidence yet. Load wiki locations above the maps.</p></div>}{boss.maps.map((p,i)=><details className="source-record" key={i}><summary><span className="source-kind">{p.role==='entrance'?'Entrance':'Arena candidate'}</span><strong>{p.title}</strong><span>Region {p.region} · {p.x}, {p.y}</span></summary><div className="source-record-body"><p>{p.caption||'No caption provided.'}</p><dl><dt>Plane</dt><dd>{p.plane??'Unknown'}</dd><dt>Map layer</dt><dd>{p.mapId??'Unspecified'}</dd><dt>Revision</dt><dd>{p.revision??'Not recorded'}</dd></dl><a href={p.source} target="_blank" rel="noreferrer">Open wiki source ↗</a></div></details>)}{!!boss.warnings.length&&<details className="inspector-disclosure"><summary>Import notes ({boss.warnings.length})</summary>{boss.warnings.map((w,i)=><p className="warning" key={i}>{w}</p>)}</details>}{!!boss.links.length&&<details className="inspector-disclosure"><summary>Related wiki pages</summary>{boss.links.slice(0,12).map(t=><a className="related" key={t} href={`https://oldschool.runescape.wiki/w/${encodeURIComponent(t.replaceAll(' ','_'))}`} target="_blank" rel="noreferrer">{t} ↗</a>)}</details>}</div>;
}
